const modules = [
  {name:'Document Module', detail:'PDF ingestion · parsing · chunking', status:'Complete', kind:'done'},
  {name:'Retrieval Module', detail:'SentenceTransformer → ChromaDB · semantic search', status:'Complete', kind:'done'},
  {name:'LLM Module', detail:'Source-linked answers · DeepSeek / Qwen / OpenAI APIs', status:'Connecting APIs', kind:'active'},
  {name:'Evaluation Module', detail:'Grounding · hallucination checks · human feedback', status:'Planned', kind:'planned'},
];
export function ResearchArchitecture(){return <div className="research-architecture">
  <div className="visual-caption"><span>RESEARCHCOMPASS</span><span>MODULAR ARCHITECTURE</span></div>
  <p className="architecture-intro">Independent components.<br/><strong>One connected research workflow.</strong></p>
  <ol className="module-flow">{modules.map((m,i)=><li key={m.name} className={`module-node module-${m.kind}`}><div><span className="module-number">0{i+1}</span><strong>{m.name}</strong><span className="module-status">{m.status}</span></div><p>{m.detail}</p></li>)}</ol>
  <div className="workspace-modules"><p className="module-group-label">PLANNED WORKSPACE & INTELLIGENCE</p><div className="module-node module-planned"><div><span className="module-number">05</span><strong>Memory Module</strong></div><p>Retain research context · memory checks</p></div><div className="module-node module-planned"><div><span className="module-number">06</span><strong>Research Notebook</strong></div><p>Paper collections · organized research notes</p></div><div className="module-node module-planned"><div><span className="module-number">07</span><strong>Research Intelligence Module</strong></div><p>Compare papers · suggest readings · explore gaps</p></div></div>
  <details className="architecture-details"><summary>Development roadmap <span>+</span></summary><ol className="research-roadmap"><li><strong>01 · Core</strong><span>PDF ingestion, document parsing, vector database, core RAG assistant, and semantic retrieval completed. LLM API connections in progress.</span></li><li><strong>02 · Evaluation <em>Planned</em></strong><span>Automated evaluation, citation grounding, hallucination detection, and human feedback.</span></li><li><strong>03 · Research workspace <em>Planned</em></strong><span>Memory checks and paper collections; further scope to be defined.</span></li><li><strong>04 · Research intelligence <em>Planned</em></strong><span>Paper comparison, research gap analysis, knowledge graphs, and paper recommendations.</span></li></ol></details>
  <details className="architecture-details"><summary>Technology stack <span>+</span></summary><dl className="architecture-stack">{[['Backend','Python'],['AI APIs','DeepSeek · Qwen · OpenAI (integration in progress)'],['Retrieval','ChromaDB now · FAISS alternative'],['Embeddings','SentenceTransformer'],['Evaluation','RAGAS · DeepEval (planned)'],['Database','PostgreSQL / SQLite'],['Frontend','Streamlit']].map(([label,value])=><div key={label}><dt>{label}</dt><dd>{value}</dd></div>)}</dl></details>
  <p className="architecture-caption">Designed to let modules be reused, replaced, and extended as the project grows.</p>
</div>}
